# Streamlit configuration for deployment
[server]
headless = true
address = "0.0.0.0"

# Disable features that might cause issues in cloud
enableCORS = false
enableXsrfProtection = true

# Performance settings
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[client]
caching = true
showSidebarNavigation = true

# Allow external resources (fonts, etc.)
enableCORS = true

[global]
developmentMode = false
showWarningOnDirectExecution = false

[theme]
base = "dark"
