[theme]
# Dark theme configuration for Streamlit
primaryColor = "#FF6B35"        # Primary color (hot orange)
backgroundColor = "#0E1117"      # Background color (dark)
secondaryBackgroundColor = "#1E1E1E"  # Secondary background color (dark gray)
textColor = "#FAFAFA"            # Text color (light white)

[server]
# Server settings
# Note: Port is managed by Streamlit Cloud automatically
address = "0.0.0.0"
headless = true
enableXsrfProtection = true
enableCORS = false

# Performance optimizations for Streamlit Cloud
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = true

[browser]
# Browser settings
gatherUsageStats = false

[global]
# Global settings
developmentMode = false
